### ISSUE TITLE
Terminal toggle hotkey activates in terminal mode

### ISSUE THREAD

**Issue by CatThingy** [NvChad/extensions#12]
In terminal mode, pressing `space+h` or `space+v` hides the terminal. This occurs fairly commonly when typing, resulting in the terminal hiding when it's not intended to.

The hotkey being present in terminal mode also results in a delay between a press of the spacebar and the character showing up in the terminal.

**Comment by siduck** [comment]
this will happen when you type space+h very very fast. just change those keys then. Check nvterm config
