### ISSUE TITLE
Feature Request: Custom Autocmd Event on Reload Theme

### ISSUE THREAD

**Issue by shaun-mathew** [NvChad/extensions#34]
**Is your feature request related to a problem? Please describe.**
I'd like to run some custom logic whenever NvChad reloads or changes its theme.

**Describe the solution you'd like**
A simple user autocmd event like NvChadThemeLoaded: 
```vim
doautocmd User NvChadThemeLoaded
```

**Describe alternatives you've considered**
I've considered using the vanilla ColorScheme autocmd, but NvChad doesn't trigger this event when changing themes or cycling
through themes in NvChad's telescope themes.

**Comment by siduck** [comment]
you can send a PR!

https://github.com/NvChad/extensions/blob/main/lua/nvchad/reload_theme.lua

**Comment by siduck** [comment]
check the core/initl.lua of nvchad config for lua autocmd examples
