### ISSUE TITLE
custom theme dir

### ISSUE THREAD

**Issue by siduck** [NvChad/extensions#4]
It would be great if we added a custom theme dir path as an option in the chadrc 

something like this : 

![image](https://user-images.githubusercontent.com/59060246/139169176-bf818399-cdab-4798-9805-a271ceda18b6.png)

And the custom folder must have the user's theme folders , which must have 2 folders : 

hl_themes 
themes 

![image](https://user-images.githubusercontent.com/59060246/139169109-3db3554b-9319-49c4-8590-b6d3e64ddf99.png)

**Comment by G-Rowell** [comment]
Should we have a set of default folders for the user?

(all within `lua/custom`)
like if there is a `autorun` folder, then lua call all files in it?
if there is a `themes` folder, then import all themes?

**Comment by siduck** [comment]
> Should we have a set of default folders for the user?
> 
> (all within `lua/custom`) like if there is a `autorun` folder, then lua call all files in it? if there is a `themes` folder, then import all themes?

yes a themes folder in the custom folder would be great

**Comment by siduck** [comment]
moved to https://github.com/NvChad/NvChad/issues/631
