### ISSUE TITLE
First :NvChadUpdate always with error

### ISSUE THREAD

**Issue by honyani** [NvChad/extensions#47]
First :NvChadUpdate always with error, after first try update without an error, but I don't sure that it pull some changes from the repo.

![IMAGE 2023-04-06 01:04:16](https://user-images.githubusercontent.com/118450997/230222146-f9833db5-a677-4333-9ecf-16b259b58ec4.jpg)

MacOS
nvim 0.9.0 (on 0.8.3 the same problem)

**Comment by siduck** [comment]
can confirm, i face this issue too. will fix this weekend. but dont worry nvchad does update. You can confirm it by checking latest commit ( leader + cm )

**Comment by siduck** [comment]
@kingavatar Can you look into this when free? https://github.com/NvChad/extensions/blob/v2.0/lua/nvchad/update.lua 

updater does this 

- git fetch 
- keep showing spinner icon till git fetch finishes
- once git fetch finishes,  parse the git commit list from git log 
- then git pull

**Comment by siduck** [comment]
@honyani should be fixed by now ig
