### ISSUE TITLE
Creating custom themes will overwrite builtin themes

### ISSUE THREAD

**Issue by ariefra** [NvChad/extensions#48]
**Describe the bug**
Creating custom themes will overwrite builtin themes

**To Reproduce**
1. Make 1 or more custom theme in `custom/themes` folder
2. Restart `nvim`
3. Change theme via shortcut or `:Telescope themes`
4. Custom themes will appear in the first list disregarding sorting and it overwrites builtin themes (i.e. aquarium)

**Expected behavior**
- Custom themes should not overwrite builtin themes
- Custom themes should appear sorted accordingly

**Software:**
- NvChad Latest update
- neovim 0.9.0

**Comment by siduck** [comment]
@ariefra fixed
