### ISSUE TITLE
Changing themes does not work, if Telescope theme preview is not visible

### ISSUE THREAD

**Issue by ariefra** [NvChad/extensions#49]
**Describe the bug**
Changing themes does not work, if Telescope theme preview is not visible.
This behaviour occur when NvChad windows is not wide enough to show Telescope theme preview. 

**To Reproduce**
1. Open terminal with approximately max. 115 char wide
2. Open nvim NvChad
3. Open theme selector by shortcut or `:Telescope themes`, observe if preview window already gone
4. Observe Bug: Scrolling down to select any theme, theme preview does not work
5. Observe Bug: Press enter to apply theme, does not work, theme still uses previous active theme

**Expected behavior**
- Selected theme should be applied, regardless telescope preview visible or not
- Eventhough preview window not visible, color changes preview should still work & visible, during scrolling to select theme

**Desktop (please complete the following information):**
 - Distro: Arch linux latest update
 - Terminal & value of $TERM: Foot
 - Version of Neovim: 0.9.0
 - NvChad: Latest update

**Comment by siduck** [comment]
@ariefra can you show a video of the behavior?

**Comment by siduck** [comment]
https://github.com/NvChad/extensions/assets/59060246/2742d33e-1c50-4374-9207-bec6cefc7605

Unable to reproduce
