### ISSUE TITLE
show documentation , mappings cheatsheet internally  

### ISSUE THREAD

**Issue by siduck** [NvChad/extensions#5]
**Is your feature request related to a problem? Please describe.**
No just an idea

**Describe the solution you'd like**
Maybe implement an install script to setup the config files automatically, could also be useful for #354 
could also mention where the documentation is, maybe add like a nvchad --help command? 
nvchad --mappings command? 

**Describe alternatives you've considered**
none I was just thinking

**Additional context**
This probably will be denied but I thought it was a good idea.

**Comment by siduck** [comment]
moved from https://github.com/NvChad/NvChad/issues/582

**Comment by peppapig450** [comment]
Would writing it in python be fine? I am sure there is a library for lua integration for python, and if not can't you use python for neovim with python-nvim installed?

**Comment by siduck** [comment]
> Would writing it in python be fine? I am sure there is a library for lua integration for python, and if not can't you use python for neovim with python-nvim installed?
I dont think so :p

**Comment by siduck** [comment]
gotta make it in full lua for sure!

**Comment by peppapig450** [comment]
damn then idk how to do it, my lua skills are 0

**Comment by siduck** [comment]
> damn then idk how to do it, my lua skills are 0

you can still learn it tho, ig it looks similar to python

**Comment by siduck** [comment]
@peppapig450 i gave up writing this feature , thought of using a plugin for it.

how does this look?

![image](https://user-images.githubusercontent.com/59060246/141678586-422975a7-df99-4549-997c-a7f80e07d05f.png)

**Comment by peppapig450** [comment]
What plugin is that?

**Comment by siduck** [comment]
> What plugin is that?

cheatsheet.nvim , but nvm it , my friend's working on something better. btw can you test the dev branch for me? 
![image](https://user-images.githubusercontent.com/59060246/141707251-3bcb741f-73bd-4353-8df4-b371445472be.png)

just change this and then do 

packersync + space uu + packersync

**Comment by peppapig450** [comment]
Yeah lemme test it in a vm rq

**Comment by peppapig450** [comment]
Just did it and got no errors so far, let me try using it

**Comment by peppapig450** [comment]
Everything works fine

**Comment by siduck** [comment]
> Everything works fine

check again? do space uu and packersync. 

and then remove this line from chadrc 

![image](https://user-images.githubusercontent.com/59060246/141825416-7869fc59-900b-4f6e-b868-993b58adb23e.png)

**Comment by siduck** [comment]
Im asking this cuz recently some cleaning has been done.

https://github.com/NvChad/NvChad/commit/1567a9c73a7e1f25ca571db53cd6e430813bef37

**Comment by peppapig450** [comment]
lsp still works and dashboard still works which is what is set in my chadrc

**Comment by siduck** [comment]
> lsp still works and dashboard still works which is what is set in my chadrc

hmm  so I assume everything's working fine right?

**Comment by peppapig450** [comment]
Yep everything working fine

**Comment by siduck** [comment]
@peppapig450 for now just keep our site repo cloned locally and use glow 
![image](https://user-images.githubusercontent.com/59060246/142562175-6dec747a-8dc8-40d2-9140-6b7d09d6caa2.png)

**Comment by siduck** [comment]
the cheatsheet initially looks like this https://cdn.discordapp.com/attachments/890224370226696234/909762427321720912/Screen_Shot_2021-11-15_at_12.10.56.png

it'll take a while for my friend to make it so wait up!

**Comment by peppapig450** [comment]
that looks rlly good

**Comment by siduck** [comment]
@peppapig450 

![image](https://user-images.githubusercontent.com/59060246/144716155-2e1fba12-ac04-4d5c-9cbf-474f56e9d71d.png)

![image](https://user-images.githubusercontent.com/59060246/144716157-a96d0aed-5d59-4c96-9468-5bd0d3031f55.png)

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/6347a00023002fa4d609cfebd031c14d6618f32c , update your dev branch and type leader ch to invoke the cheatsheet

**Comment by peppapig450** [comment]
I can't get the dev branch to update

https://user-images.githubusercontent.com/55930078/144724420-9b54c1d5-539c-4586-a689-352ae8edd1bc.mp4

**Comment by peppapig450** [comment]
Okay I just realized I had it set wrong it was supposed to be M.options not M.plugins and I fixed it but now i got this.
![image](https://user-images.githubusercontent.com/55930078/144724669-3549404a-c727-4527-bd2c-e47b788537b1.png)

**Comment by siduck** [comment]
did you edit files outside custom dir?

**Comment by siduck** [comment]
just do a git pull

**Comment by peppapig450** [comment]
I installed NvChad on a new vm and same error still happens 

![image](https://user-images.githubusercontent.com/55930078/144729513-dc03fe64-9c77-4837-b7c3-2a49f58f8cbe.png)

**Comment by siduck** [comment]
weird  ,it works for me. can you for now just try git clone dev branch and move your custom folder into it?

**Comment by peppapig450** [comment]
yes I can in a bit im busy rn

**Comment by peppapig450** [comment]
![image](https://user-images.githubusercontent.com/55930078/144733930-b845590b-e919-4cbf-99c3-608575e2733a.png)

**Comment by alaindresse** [comment]
I tried this and it looks nice !
The plugin mappings however no longer show on second try. To reproduce,

- take a brand new nvchad install (no custom),
- type <leader>ch to see the complete mapping
- quit (I typed q)
- type <leader>ch again ==> only the normal mappings are shown

**Comment by G-Rowell** [comment]
@alaindresse 

Should be fixed by https://github.com/NvChad/extensions/pull/8


Hope this helps!!! :grin:
